'use strict';
/* Builds src/data/atlas.js: the structure of the six papers (code, tier, format, repeated template per slot) with the
   template(s) that reproduce each slot. Structure only — no real item text, numbers or answers are shipped.
   usage: node tools/build-atlas.js <atlas_raw.json> */
const fs = require('fs'), path = require('path');
const QF = require('../src/index.js');
const raw = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
const MON = { Dec: 'dec', Jan: 'jan', Mar: 'mar', Apr: 'apr', Jun: 'jun', undated: 'und' };
const map = {};
for (const t of QF.templateList) {
  if (t.level !== '=') continue;
  const re = /(Dec|Jan|Mar|Apr|Jun|undated) Q(\d+)/g; let m;
  while ((m = re.exec(t.basis || ''))) { const k = MON[m[1]] + ':' + m[2]; (map[k] = map[k] || []).push(t.id); }
}
const REP = {}; QF.templateList.forEach(t => { if (t.rep && !REP[t.rep]) REP[t.rep] = t.id; });
const FALLBACK = { 'und:11': ['INQ-rat.closed'], 'und:29': ['TR-graph.stmt'] };
const LABEL = { dec: 'December 2025', jan: '25 January 2026', mar: '15 March 2026', apr: '25 April 2026', jun: '27 June 2026', und: 'Undated paper' };
const BP = { dec: 'A', jan: 'A', mar: 'A', apr: 'B', jun: 'B', und: 'A' };
const out = {}, notes = [];
for (const p of Object.keys(raw)) {
  out[p] = raw[p].map(s => {
    let ids = (map[p + ':' + s.q] || []).filter(id => QF.templates[id].code === s.code);
    if (!ids.length && s.rep && REP[s.rep] && QF.templates[REP[s.rep]].code === s.code) ids = [REP[s.rep]];
    if (!ids.length && FALLBACK[p + ':' + s.q]) ids = FALLBACK[p + ':' + s.q];
    if (!ids.length) { notes.push('NO TEMPLATE ' + p + ' Q' + s.q + ' ' + s.code); }
    ids.forEach(id => {
      const t = QF.templates[id];
      if (t.fmt !== s.fmt) notes.push('format ' + p + ' Q' + s.q + ' ' + s.code + ': slot ' + s.fmt + ' vs ' + id + ' ' + t.fmt);
      if (t.tier !== s.tier) notes.push('tier   ' + p + ' Q' + s.q + ' ' + s.code + ': slot ' + s.tier + ' vs ' + id + ' ' + t.tier);
      if ((t.rep || null) !== (s.rep || null)) notes.push('repeat ' + p + ' Q' + s.q + ' ' + s.code + ': slot ' + s.rep + ' vs ' + id + ' ' + t.rep);
    });
    return { q: s.q, code: s.code, tier: s.tier, fmt: s.fmt, rep: s.rep || null, tpl: ids };
  });
}
notes.forEach(n => console.log(n));
const lines = [];
lines.push('/* ACE CSCA Question Factory · data/atlas.js — generated by tools/build-atlas.js from the Exam Structure Atlas.');
lines.push(' * The structure of the five real sittings and the undated paper: for every slot its sub-domain code, tier, format,');
lines.push(' * repeated-template id and the template(s) that reproduce the form. No real item text, number or answer is stored. */');
lines.push(';(function (root) {');
lines.push("  'use strict';");
lines.push('  var QF = root.QF = root.QF || {};');
lines.push('  function P(rows) { return rows.map(function (r) { return { q: r[0], code: r[1], tier: r[2], fmt: r[3], rep: r[4], tpl: r[5] }; }); }');
lines.push('  QF.atlas = {');
lines.push("    order: ['dec', 'jan', 'mar', 'apr', 'jun', 'und'],");
lines.push('    papers: {');
Object.keys(out).forEach((p, i, arr) => {
  lines.push('      ' + p + ": { label: '" + LABEL[p] + "', blueprint: '" + BP[p] + "', slots: P([");
  out[p].forEach((s, j) => lines.push('        ' + JSON.stringify([s.q, s.code, s.tier, s.fmt, s.rep, s.tpl]).replace(/"/g, "'") + (j < 47 ? ',' : '')));
  lines.push('      ]) }' + (i < arr.length - 1 ? ',' : ''));
});
lines.push('    },');
lines.push('    /** domain quotas of the two blueprints (Atlas): A = Dec, Jan, undated (March = A with one FN item traded for TR); B = Apr, Jun */');
lines.push('    blueprints: {');
lines.push('      A: { SI: 5, FN: 9, TR: 10, SQ: 6, LN: 9, CN: 6, VEC: 1, CPX: 1, PRB: 1 },');
lines.push('      B: { SI: 5, FN: 8, TR: 10, SQ: 8, LN: 8, CN: 6, VEC: 1, CPX: 1, PRB: 1 }');
lines.push('    },');
lines.push('    /** repeated templates R01–R14 -> the template that reproduces them */');
lines.push('    repeats: ' + JSON.stringify(REP).replace(/"/g, "'").replace(/,/g, ', ') + ',');
lines.push("    /** site papers (Course Plan §9): every one is exactly at exam level */");
lines.push("    site: { diagnostic: 'dec', 'mock-1': 'jan', 'mock-2': 'mar', 'mock-3': 'apr', 'mock-4': 'jun' }");
lines.push('  };');
lines.push("})(typeof globalThis !== 'undefined' ? globalThis : this);");
fs.writeFileSync(path.join(__dirname, '../src/data/atlas.js'), lines.join('\n') + '\n');
console.log('written src/data/atlas.js', Object.keys(out).map(p => p + ':' + out[p].length).join(' '), 'notes:', notes.length);
